#!/bin/bash

#Submit this script with: sbatch -A oceanphysics job_script_name

#SBATCH --time=12:00:00   # walltime
#SBATCH --ntasks=50  # number of processor cores (i.e. tasks)
#SBATCH --nodes=4   # number of nodes
#SBATCH --mem-per-cpu=6G   # memory per CPU core
#SBATCH --mail-user=ilopezgo@caltech.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH -J "ekp_50"   # job name

module purge
module load julia/1.5.2 hdf5/1.10.1 netcdf-c/4.6.1 openmpi/4.0.1
julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.API.precompile()'

#julia --project -e 'push!(LOAD_PATH, "@pkglock"); using PkgLock; PkgLock.instantiate_precompile()'
julia --project -p 50 calibrate.jl
